### ISSUE TITLE
Adding Face Contour 

### ISSUE THREAD

**Issue by Loopex2019** [santetis/flutter_camera_ml_vision#33]
I have a request can you add please the Face Contour Feature to the Camera Ml ?

**Comment by kevin-sakemaer** [comment]
The goal of this package is to provide the camera preview with the firebase_ml_vision detection.
What the user do after that is up to the user. We don't provide such fonctionality because this part is highly customizable.
If you need something like that our support can add it directly to your application.
cc @bwnyasse

**Comment by Loopex2019** [comment]
Okay thanks.

**Comment by kevin-sakemaer** [comment]
Hi @Loopex2019,
we just added an example on how to detect face and add contour above the preview :)
The code is [here](https://github.com/rushio-consulting/flutter_camera_ml_vision/blob/master/example/lib/main_face.dart).
