### ISSUE TITLE
Example is not working!!!

### ISSUE THREAD

**Issue by NTMS2017** [santetis/flutter_camera_ml_vision#42]
Example is not working as well as is not shows any error. 

I created a new project and copy the example code from plugin page as well as follow the README.md. I get AndroidX error and fix that with following link. (https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility) 

I might have a problem on Configure Firebase section.

Do you have any good basic tutorial how to Configure Firebase to use your plugin? Thanks

**Note:** To me the Firebase console is not clear so I am having difficulty to follow how to configure. Step-by-step tutorial will be perfect people like me.

**Comment by bwnyasse** [comment]
hello @NTMS2017 ,

after reading your question , I would suggest you to contact the [support](https://rushio-consulting.fr/support/). Today rushio-consulting provide **support** to help you develop extra features not covered by their open source projects.

Helping you with Firebase won't be answered in the open source project. So, you can clearly explain your requirements to the support. And I Guess if it IS something the team Can covered, they will send you an invoice ( because the technical support is not free ).

Bests regards.
